#dubbo注册 订阅 相关
dubbo:
  #服务注册地址（注册到spring-cloud的注册服务器上）
  registry:
    address: spring-cloud://localhost
  #扫描service实现类路径
  scan:
    base-packages: com.sg.order.service.impl
  protocol:
    name: dubbo
    port: -1
    #订阅的服务 英文 “,”分割  不需要调用dubbo接口的可以注释掉
  cloud:
    subscribed-services:
    #设置启动时不检测订阅的服务状态
  consumer:
    check: false